### PR TITLE
elasticsearch 2.x port

### PR DESCRIPTION
**Pull request by joelstewart**
I have the plugin working with elasticsearch 2.x..

The work here was branched from the 2.6.2 tag, and I changed the artifact names to append -2x.   Not really sure if you care to maintain a 2x version as a separate branch, project, what not...  I'm actually not really sure about any of the pom versions in this pull....  

My goal was first to get the unit tests to pass.  then to see if i could actually create a layer in geoserver.

The only other change you need that is not captured in this pull is to upgrade guava to v18 in the geoserver war lib.

If you have the time, I'd love to talk about this plugin and any lessons / warnings you might have.  I might even be willing to do more maintenance work on it...

Thanks for putting this code up on github

jcstewart@integrity-apps.com

### CODE REVIEW

**Comment by sjudeng** [comment]
Hi Joel,

This is great. Glad to have you as a contributor and thanks for taking the time on unit tests and documentation.

I'll need to take some time to get this merged in. I'm going to branch master to 2.7-SNAPSHOT, bump master version to 2.8-SNAPSHOT, and then I'm hoping to be able to merge your branch into master. There are a number of major fixes/improvements on the geoserver/geotools side that are missing from the 2.6-SNAPSHOT branch.

I think currently the plugin works with any Elasticsearch 1.x client lib version, but I'm assuming some of these changes aren't compatible with 1.x clients? If not, I still suggest we move forward with the above ... the 2.6/2.7 branches will still be there if someone wants 1.x compatibility.

One question from looking over commit and comments, I thought Elasticsearch filters, versus queries, would be more appropriate for OGC filtering. See examples and performance notes in the below Elasticsearch documentation. Note that native queries can still be passed through directly if scoring is important.

https://www.elastic.co/guide/en/elasticsearch/guide/current/_queries_and_filters.html

One other thing, it would be great if you could fix the indentation in FilterToElasticHelper to make the merge cleaner. I'm just expecting a painful merge into master, given I think there were quite a few changes there that were not backported into 2.6-SNAPSHOT.

Looking forward to getting this in. It's a great contribution. Thanks for your work on this!

**Comment by joelstewart** [comment]
The 2.x api Eliminates FilterBuilder.  So things like "AndFilter" are gone, and you are stuck with "BoolQuery.must...".   So that was the majority of the FilterToElastic modification.  It was good to see a healthy number of unit tests - that made a quick stab at it feasible...

I am not sure I totally understand the filter context / query context that is discussed here: https://www.elastic.co/guide/en/elasticsearch/reference/2.x/query-filter-context.html

I recommend we both review that and... 

https://www.elastic.co/blog/found-optimizing-elasticsearch-searches

It is very likely I am making mistakes!  I am scratching my head a bit about why we would want post filters, instead of filtered queries.  So I think it might be prudent to revisit if we are wanting to build filters for post filtering, or make them part of the query itself.  Maybe there is something fundamental in how the visit pattern works that makes that a hard to do thing??  I just can't say I have my head fully wrapped around the problem yet.

I will continue to update the forked project.   And I will definitely address the couple places where there was indentation changes..

The primary point of making a merge request this early was to get dialog going about these things.

regards.

**Comment by joelstewart** [comment]
indentation changes fixed.

BTW - I've been experimenting with not using the post filter, and it seems to work.  The 1.x version of elasticgeo would create queries like this:

ORIG VERSION - Query: {"match_all":{}}
ORIG VERSION - post : {"geo_shape":{"geo3":{"shape":{"type":"point","coordinates":[0.0,0.0]},"relation":"disjoint"},"_name":null}}

Leaving as a post query would look in my port would look the same:
2.x VERSION - Query: {"match_all":{}}
2.x VERSION - post : {"geo_shape":{"geo3":{"shape":{"type":"point","coordinates":[0.0,0.0]},"relation":"disjoint"},"_name":null}}

Pushing the filter into the query would take advantage of filter cache, and would look:
NEW VERSION: {"bool":{"must":{"match_all":{}},"filter":{"geo_shape":{"geo3":{"shape":{"type":"point","coordinates":[0.0,0.0]},"relation":"disjoint"},"_name":null}}}}

From what I gather, the only reason to use post-filter is if you want to create aggregations to include a broader set of things than what will show in "hits".  But maybe I am missing something.  Could you explain to me why post filter is used in elasticgeo?

**Comment by sjudeng** [comment]
This is my mistake. I hadn't realized that the filter could be applied as part of the query versus after the query. Filtered queries definitely look like the way to go. When I saw the QueryBuilder updates I was thinking in 1x API terms, versus in 2x where it looks like queries and filters have been largely merged. As long as all OGC filtering is being mapped to the filter element in the query, I'm good.

Sorry for my confusion. Thanks for pushing on this.

**Comment by joelstewart** [comment]
How about a version bump to elasticgeo, and for elasticgeo 3.x require Elasticsearch > 2.x.  I think when you see the improvements Elasticsearch is making in geo, most are going to want to get to a 2.2 minimum.  (see https://www.elastic.co/blog/supercharging-geopoint ).  

I originally did the work from the 2.6 tag, but I see there are quite a few more tests in the 2.7 snapshot.  Any plans on when that might be released? 

I will make the change to use filtered queries rather than post-filters, and I will clean up the code a bit. If it makes more sense, I can maintain the 2x version a while, trailing any releases you have with -elastic2x.  For example, the 2x port branch, when I am happy with it, could be tagged and released as 2.6.2-elastic2x  .    What makes the most sense to you?

**Comment by sjudeng** [comment]
The performance metrics for Elasticsearch 2.2 do look impressive. My thoughts exactly on bumping the project version and requiring Elasticsearch > 2.x going forward. I was going to go to 2.8-SNAPSHOT to keep in line with GeoServer versioning.

I just tagged a new release, 2.7.4. I'm not sure if you want to do any work to merge this into your branch. It's up to you. Like I said, I'm expecting some pain with the merge, given how many commits ahead it is from 2.6.2.

**Comment by joelstewart** [comment]
I think what I will do is 2 things:
1) Go ahead and tag and release the 2.6.2-es2x on the fork soon.  I'm using it now in a dev env.
2) Wait until 2.2 is released by elasticsearch, then merge with your 2.7.4 upstream - and get it all merged up and release that as  2.7.4-es2x.  Hopefully it will not be too nasty to merge together.  If it is, I will probably do the same, take the 2.7.4 tag, branch, and do the modifications from scratch.

Let me know if there is something I can do to prepare for a 3.x pull at some point.

**Comment by sjudeng** [comment]
I started work on the merge (see the 'elasticsearch2-dev' branch). The unit tests are passing, though I had to skip one relating to parsing invalid geohash values. It looks like invalid values no longer throw an exception in the new Elasticsearch API.

**Comment by joelstewart** [comment]
ok.   i posted a release on the fork project.  only after putting it in did I catch on the versions of elasticgeo track geoserver.  

I'll check out the 2x dev branch, and make future merge requests to it I see something.

**Comment by sjudeng** [comment]
I'm interested in possibly maintaining a single branch that supports both Elasticsearch 1.x and 2.x. See the 'elastisearch12-dev' branch below. This builds different plugin versions based on a Maven profile flag. As you can see, it required more complicated project and build configurations. Question is whether it's harder to maintain two branches or a single larger branch. Thoughts?

https://github.com/ngageoint/elasticgeo/tree/elasticsearch12-dev

**Comment by joelstewart** [comment]
I was thinking that could be a way to go.  

What about continuing with the service loader pattern?  You would have two projects that provide org.geotools.data.DataStoreFactorySpi in meta-inf.   They could both use a common / core project to get the fluff out and only implement what is specific to that version.

Tricky part might be unit testing.  While the FilterToElastic is a good unit test that does not need a running elasticsearch node, the others are more functional tests.  You have 2 choices, duplicate the code to test in each impl project, or introduce a fourth (e.g. parent).  The parent would not have any source, but would exist to, based on maven profile, test the functional capabilities.  Still a jar project, just nothing would be in source and no other project would use it as a dependency.  

Something with maven profiles would change dependencies around so builds and assemblies would do one or the other, but never both.

**Comment by sjudeng** [comment]
I tried both ways, but the 'elasticseach12-dev' branch goes with the latter approach, which turned out to be cleaner I think. There's a common module (gt-elasticsearch-core), two implementations (gt-elasticsearch1, gt-elasticearch2) and a main module (gt-elasticsearch). The functional tests are all in the main module, which builds and tests against elasticsearch2 by default, or elasticsearch1 if the profile is specified. The main module jars include a classifier, which is used when building the GeoServer plugin.

```bash
cd elasticgeo
mvn clean install [-Pelasticsearch1]
cd gs-web-elasticsearch
mvn package -P deploy[,elasticsearch1]
```

**Comment by joelstewart** [comment]
It works.  

I am thinking of it a bit differently.  But it would be a bigger refactor.  It would come without the need for classifiers or to clean before building for a second profile, but it would come at the cost of having a lot more to abstract.

**Comment by sjudeng** [comment]
Did you have to update GeoServer from guava-17.0 to guava-18.0 to get the plugin to work with Elasticsearch 2.x? I ran into this during testing.

**Comment by joelstewart** [comment]
I did.  The way I did it was to suggest removing it in the geoserver war.  I am just not sure about the classloading in geoserver to know if replacing it in the shade - plugin built gs-web plugin jar would work, I did not try that approach.

https://github.com/joelstewart/elasticgeo/blob/2_x_port/README-es2x.md

**Comment by joelstewart** [comment]
2 informational updates on this effort.  

1) ES will have an official http client in the coming months.  This should help in jar hell issues (guava, e.g.)  and may even be agnostic enough between 1.x and 2.x.  

2) Unless distance_error_pct is set to 0 (which happens when using other than default precision), one would need to have the filter as a post filter to eliminate false positives.  To get the best of both worlds (take advantage of filter caching and have no false positives) one would put the filter both as a part of the filtered query and again as a post filter.

**Comment by sjudeng** [comment]
Thanks for the updates. I'd like to get a test in there to reproduce the issue with non-zero distance_error_pct. I'll look at this in the coming weeks, or let me know if you want to take it and submit another PR.

**Comment by sjudeng** [comment]
Having just updated to Elasticsearch 5 it seems like it's probably time to finally close this. I had created the test for distance_error_pct (see below) but I still got the false postive returned even when including the post filter and I never got back around to seeing if there were other options. Anyway thanks again for your contribution.

Test case
```java
@Test
public void testDistErrPct() throws Exception {
    init("not-active","geo5");
    FilterFactory2 ff = (FilterFactory2) dataStore.getFilterFactory();
    GeometryFactory gf = new GeometryFactory();
    Point pt = gf.createPoint(new Coordinate(1.49,1.5));
    Intersects f = ff.intersects(ff.property("geo5"), ff.literal(pt));
    SimpleFeatureCollection features = featureSource.getFeatures(f);
    assertEquals(0, features.size());
}
```

Test mapping definition
```javascript
{"geo5": {"type": "geo_shape", "tree": "quadtree", "precision": "10m", "distance_error_pct": "0.5"}}
```

Test geometry
```javascript
{"geo5": {"type": "polygon", "coordinates": [[[1, 1], [3, 1], [4, 2], [2, 2], [1, 1]]]}}
```

**Pull request closed without merging**
